//
//  FindDifference_389.m
//  LeetCode_Solutions
//
//  Created by 来自遥远星系的核心巡洋舰 on 16/10/9.
//  Copyright © 2016年 KnightJoker. All rights reserved.
//


/*  question of description
 
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 
 Example:
 
 Input:
 s = "abcd"
 t = "abcde"
 
 Output:
 e
 
 Explanation:
 'e' is the letter that was added.
 
 */

#import "FindDifference_389.h"

@implementation FindDifference_389

- (unichar)findTheDifference:(NSString *)s
                         and:(NSString *)t {

    for (int i = 0; i < s.length; i++) {
        
        if ([s characterAtIndex:i] != [t characterAtIndex:i]) {
            return [t characterAtIndex:i];
        }

    }
    return [t characterAtIndex:s.length];
}

@end
